# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:
date_format: "ordinal"
title: 逸涵
subtitle: "welcome to my blog"
description: "我的第一个博客"
keywords: 大学生
timezone: Asia/Beijing
encoding: "utf-8"
since: 2024
repository: myh11/myh11.github.io

cdn:
  jsdelivr:
    enabled: false

components:
  share:
    enabled: false
    hide-platforms: qq,facebook
  busuanzi:
    enabled: false
    start_date: 2020-05-03
  side_bar_repo:
    enabled: true
    limit: 5
  word_count:
    enabled: true
  qrcode:
    enabled: false
    image_alt: 闷骚的程序员
  wiki:
    view: cate
  fancybox:
    enabled: false

compress_html:
  clippings: all
  comments: ["<!--", "-->"]
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: myh
organization:
organization_url:
github_username: myh
location: Beijing, China
email: myh@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  - href: /
    label: 首页
  - href: /categories/
    label: 分类
  - href: /archives/
    label: 归档
    mobile-hidden: true
  - href: /open-source/
    label: 开源
  - href: /fragments/
    label: 片段
  - href: /wiki/
    label: 维基
  - href: /links/
    label: 链接
    mobile-hidden: true
  - href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
  banner:
    color: "#fff"
    nav-color: "rgba(255, 255, 255, .5)"
    background-color: "#4183c4"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "<!--more-->"
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
collections:
  wiki:
    output: true
    permalink: /wiki/:path/
  fragments:
    output: true
    permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: giscus
giscus:
  repo: Myh11/Myh11.github.io
  repo-id: R_kgDOM3iJ-w
  category: Q&A
  category-id: DIC_kwDOM3iJ-84Ci0EA

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
  fulltext: false
  limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
  analytics_id:
  adsense:
    enabled: false
    footer: false
    sidebar: false
    sidebar-detail: false
    content_header: false
    content_footer: false
